@local=http://localhost:3003
 @token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIwNTU1NTU1NTU1IiwiYml6IjpmYWxzZSwiaWF0IjoxNzA2NzA5MDAyfQ.XAaLMz4tveQgoNOzPkIJVz3hEo2GjYE5hRdBBRhaHvc
//Content-Type: application/json
###
//send new user (sign in) request
POST {{local}}/users
Content-Type: application/json

{
    "name": "sagi4",
    "password": "Levy111",
    "email": "sagi4@gmail.com",
    "biz": true
  }
###


//sent req for auth (log in)
POST {{local}}/auth
Content-Type: application/json
 
{
    "password": "Levy111",
    "email": "sagi4@gmail.com"
}






###


GET {{local}}/users/me
x-auth-token:{{token}}



















###
GET {{local}}/users/me
x-auth-token:{{token}}





###
// send card req
POST {{local}}/api/tasks
x-auth-token:{{token}}

{
  "isPaid": false,
  "inCalendar": false,
  "activityName": "paintball",
  "bizUserName": "יוסי",
  "activityDescription": "paintball-game",
  "activityAddress": "kfar sava",
  "phoneNumber": "0555555555",
  "activityImage": "https://cdn.pixabay.com/photo/2017/04/11/03/28/paintball-2220450__340.jpg",
  "activityNumber": "88153918",
  "user_id": "0555545555",
  "activityDate": "2024-01-28",
  "activityTime": "18:50",}
   
 


###
GET {{local}}/cards/my-activity-cards/643ebbd08427d5bf67b98d31
x-auth-token:{{token}}
Content-Type: application/json




###
GET {{local}}/users/me
x-auth-token:{{token}}

###
# GET {{local}}/cards/my-activity-cards1
# x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDRmYzYyNWIyOTI2MWVkYzA1ZjJmNDIiLCJiaXoiOmZhbHNlLCJpYXQiOjE2ODI5NTU3MjF9.CgS4eZWZA_pfBS07HRQSBDn7CJoSIz5X3NwKdfYKYZo
# Content-Type: application/json
